### ISSUE TITLE
classification of Ger, Fr and It chords

### ISSUE THREAD

**Issue by allorens** [DCMLab/standards#19]
In its 1st version at least, the script includes the Ger, Fer and It labels in the `numeral` column. Without changing the annotation standard, wouldn't it be better to include a `vii` in that column and leave `Ger`, `Fer` and `It` for the `form` column?

**Comment by johentsch** [comment]
We made a change in v2.0 by which `Ger` and `Fr` (but not `It6`), in their standard form, can be used with or without `6` and annotation of inversions is made possible. This is achieved by moving the special symbols ('shortcuts') to a separate `special` column while replacing them with their actual meaning, as described [here in the guidelines](https://github.com/DCMLab/standards/blob/develop/guidelines/english.md#augmented-6th-chords-fr-ger-it6). Within the regex, the special symbols need to remain in the `numeral` column because it is the only obligatory feature, so the only one that can occur on its own.

**Comment by johentsch** [comment]
Inversions are allowed for `It` chords but since it is a triad, the standard form needs to be written as `It6`; `It` designates the root position `viio(b3)/V`.
