### ISSUE TITLE
Forbidden repetitions of identical labels and exceptions

### ISSUE THREAD

**Issue by johentsch** [DCMLab/standards#3]
At the moment, annotators are allowed to repeat a label to mark a phraseending, e.g. I (beginning of harmony) I\\ (end of phrase). Instead, we could allow for \\ to stand as a separate symbol, which is something that annotators sometimes do intuitively and has to be corrected so far. The change can be easily made by updating the regex with a ( )? . Would you agree on that, @fabianmoss ? This change would avoid to have _the exception_ from forbidden repetition of identical labels.

**However, ** there would still be a similar exception for organ points. We could at the same time consider to allow for organ point notation to occur independently of the onsets of harmonies. This would be quite a big change, however: 
* It would even out the discrepancy between the time points designated by `\\` and `]`
  - The phraseend marks this time point directly, but the end of the organ point occurs only when the harmony designated with `]` ends. 
  - Allowing for `]` to stand alone would make it possible to have it designate the ending of the pedal note directly instead.
  - When parsing this label, a row would be created without new chord features, showing that the previous harmony is still on. The countermodel would be that the same harmony is repeated, resulting in a new harmonic segment. This is actually a strong argument for allowing for the exception, considering that a harmony over a pedal is different from the same harmony without the pedal.

**Comment by laserjeyes** [comment]
Maybe one guiding principle to keep in mind for the discussion could be: Since every label represents a segmentation of the score, it should represent a change in harmony. The alternative would mean to allow for different levels of segmentation, e.g. allowing for singular `\\` alone would designate the end of a phrase segment but not of a harmonic segment. But this is happening at present, in any case, with the difference that the same label is repeated, e.g. `I I\\`.

**Comment by fabianmoss** [comment]
I am not quite sure if I follow your considerations. What are circumstances where you would annotate a `\\` or  `]` without a "supporting" harmony?

I don't see a problem with repeating harmonies at phrase boundaries but wouldn't it be rather `I\\ I` instead of `I I\\`? Meaning: First I conclude a phrase and then I continue with the same harmony? I can't imagine a situation in which the latter makes sense but I might just not think of the right thing.

**Comment by johentsch** [comment]
No, in `I\\ I` the second `I` is superfluous because under the current semantics (labels valid until the next label) it does not add new information. `I I\\`, however, says "here, the harmony starts, and here is where the phrase ends".
This is a very extreme case where both occur very close to each other:
![corelli op01n07a](https://user-images.githubusercontent.com/42718519/87433986-39be1880-c5ea-11ea-9716-afb19e7cab9a.png)
([Corelli op. 1/7 I](https://github.com/DCMLab/new_annotations/blob/master/annotations/Corelli/op01n07a.mscx) mm. 1-4)

Suggestions to discuss:
* Permit `\\` to stand alone
* Permit repetition of identical labels in order to perform a lower level segmentation.

**Comment by johentsch** [comment]
The new version will allow for repetition of identical labels under special circumstances _and_ for having phrase annotations occur separately.

The solution we discussed was in favor of a possibility to annotate phrase interlocking. The natural solution seems to be to annotate both phrase endings and beginnings in a way, that both symbols can be combined in one. The first suggestion was to use `\` for endings, `/` for beginnings and `\/` as combination. However, since the expressions continue to end labels, `/` would make it impossible to detect mistakes where an applied chord is missing it's secondary key, as in `V/` instead of `V/V`.

**Solution:** We suggest a solution with `{` for beginnings, `}` for endings, and `}{` for the combination. In order to distinguish phrase interlocking from "normal" phrase transitions we ask annotators to put `}`  on the beat where the phrase ends structurally (e.g. the 1 of a cadence's ultima). This way, the phrase length is still calculated until the next phrase's beginning, but we will know how much of the phrase is just a 'codetta'. As an example, here is the previous one with the suggested new notation:

![image](https://user-images.githubusercontent.com/42718519/88062187-c7f54a00-cb68-11ea-9d9e-ef430ae9fe8f.png)
